name: Tests
on: [push, pull_request]

jobs:
  test_ubuntu:
    name: Test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get -y update && sudo apt-get -y install \
            clang \
            cmake \
            build-essential \
            autoconf \
            gperf
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
  test_fedora:
    name: Test (Fedora)
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - name: Install Dependencies
        run: |
          dnf update && dnf -y install \
            clang \
            cmake \
            make \
            autoconf \
            gperf
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
  test_macos:
    name: Test (MacOS)
    runs-on: macos-latest
    steps:
      - name: Install Dependencies
        run: |
          brew install \
            gperf \
            autoconf \
            make
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
